services:
  timescaledb:
    image: timescale/timescaledb:2.25.0-pg17
    container_name: timescaledb
    environment:
      POSTGRES_USER: infoclimat
      POSTGRES_PASSWORD: infoclimat2026
      POSTGRES_DB: meteodb
    ports:
      - "5432:5432"
    volumes:
      - timescaledb-data:/var/lib/postgresql/data
      - ./timescaledb-env/meteodb_dump.sql:/docker-entrypoint-initdb.d/dump.sql:ro
    networks:
      - bd_net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U infoclimat -d meteodb"]
      interval: 10s
      timeout: 20s
      retries: 10
      start_period: 40s
    restart: unless-stopped

  nginx:
    image: nginx:1.29.5-alpine3.23-perl
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - frontend
      - backend
    networks:
      - app_net

  backend:
    build:
      context: ./backend
    env_file:
      - ./.env
    depends_on:
      timescaledb:
        condition: service_healthy
    networks:
      - app_net
      - bd_net

  frontend:
    build:
      context: ./frontend
    env_file:
      - ./.env
    networks:
      - app_net

  prometheus:
    image: prom/prometheus:v2.48.0
    container_name: prometheus
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    ports:
      - "9090:9090"
    networks:
      - app_net
    depends_on:
      - backend

  grafana:
    image: grafana/grafana:10.0.1
    container_name: grafana
    environment:
      GF_SECURITY_ADMIN_USER: "admin"
      GF_SECURITY_ADMIN_PASSWORD: "admin"
    volumes:
      - ./monitoring/grafana-datasource.yml:/etc/grafana/provisioning/datasources/datasources.yml:ro
      - ./monitoring/grafana-dashboard.yml:/etc/grafana/provisioning/dashboards/dashboard.yml:ro
      - ./monitoring/dashboard.json:/var/lib/grafana/dashboards/dashboard.json:ro
    ports:
      - "3000:3000"
    networks:
      - app_net
    depends_on:
      - prometheus

volumes:
  timescaledb-data:
    driver: local
networks:
  app_net:
  bd_net:
